version: "3.9"

services:
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-container
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json:ro
    restart: unless-stopped
